version: "3.3"
services:
  api:
    container_name: api
    restart: unless-stopped
    image: api
    command: python app/main.py
    build: .
    env_file:
      - .env
    depends_on:
      - db
  engine:
    container_name: engine
    restart: unless-stopped
    image: engine
    build: .
    command: celery -A tasks worker -P solo -c 1 -l INFO -Q ENGINE -n engine
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
  db:
    container_name: db
    restart: always
    image: postgres:13.3
    env_file:
      - .env
    volumes:
      - k-db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
volumes:
  rabbitmq-data:
  rabbitmq-log:
  k-db:
networks:
  default:
    external: true
    name: kavianex
